# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dujour-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm cache clean --force
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install server dependencies
        run: npm install
        working-directory: ./dujour-desktop/adminDashboard/server

      - name: Install client dependencies
        run: npm install
        working-directory: ./dujour-desktop/adminDashboard/client

      - name: Build client
        run: npm run build
        working-directory: ./dujour-desktop/adminDashboard/client

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D855C39570F644749206E8853D1E3CCE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA98E40EBC3B40FEBEC8CB842C0FD738 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8F1821BB5D0441B94433E7CBC60E1D2 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dujour-admin'
          slot-name: 'Production'
          package: .
          