name: Deploy Node-React App to Azure Web App

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'  # Adjust as needed

      - name: Install root dependencies
        run: npm install
        working-directory: ./dujour-mobile

      - name: Install client dependencies
        run: npm install
        working-directory: ./dujour-mobile/client

      - name: Build client
        run: npm run build
        working-directory: ./dujour-mobile/client

      - name: Install server dependencies
        run: npm install
        working-directory: ./dujour-mobile/server

      - name: Zip deployment package
        run: |
          cd ./dujour-mobile
          zip -r deploy.zip client/build server -x "*node_modules*"
          echo "Artifact zipped"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure using Azure CLI
        run: |
          az webapp deploy --resource-group dujour-mobile_group --name dujour-mobile --src-path ./dujour-mobile/deploy.zip

      - name: Install dependencies on Azure via Kudu API
        run: |
          curl -X POST https://dujour-mobile.scm.azurewebsites.net/api/command \
          -d '{"command": "npm install", "dir": "site\\wwwroot"}' \
          -H 'Authorization: Bearer ${{ secrets.AZURE_SECRET }}' \
          -H 'Content-Type: application/json'
