name: Build and deploy Node.js & React app to Azure Web App - dujour-mobile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Match this with your development environment

      - name: Install and build server
        run: |
          cd dujour-mobile/server
          npm install
          npm run build --if-present

      - name: Install and build client
        run: |
          cd dujour-mobile/client
          npm install
          npm run build

      - name: Create deployment artifact
        run: |
          mkdir deployment
          cp -R dujour-mobile/server/ deployment/server/
          cp -R dujour-mobile/client/build/ deployment/client/
          zip -r deployment.zip deployment

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: full-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: full-app

      - name: Unzip artifact for deployment
        run: unzip deployment.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dujour-mobile'
          slot-name: 'production'
          package: deployment
