name: Deploy Node-React App to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu virtual environment

    steps:
      - uses: actions/checkout@v2  # Checks out the code for your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify Node.js version
          cache: 'npm'  # Cache npm modules

      - name: Install dependencies in dujour-mobile
        run: npm install
        working-directory: ./dujour-mobile  # Runs npm install in the dujour-mobile directory

      - name: Install client dependencies
        run: npm install
        working-directory: ./dujour-mobile/client  # Runs npm install in the client subdirectory

      - name: Build client
        run: npm run build
        working-directory: ./dujour-mobile/client  # Runs build script in the client directory

      - name: Install server dependencies
        run: npm install
        working-directory: ./dujour-mobile/server  # Runs npm install in the server subdirectory

      - name: Remove non-essential node modules
        run: |
          rm -rf ./dujour-mobile/server/node_modules/@types
          rm -rf ./dujour-mobile/server/node_modules/*/test
          rm -rf ./dujour-mobile/server/node_modules/*/docs
        working-directory: ./

      - name: Zip deployment package
        run: |
          cd dujour-mobile
          zip -r deploy.zip client/build server -x "*.d.ts" -x "*test*" -x "*README.md" -x "*CHANGELOG.md"
          echo "Artifact zipped"
        working-directory: ./

      - name: List and sort contents of deploy.zip by size
        run: |
          unzip -l dujour-mobile/deploy.zip | awk 'NR > 3 && NF {print $1 " " $4}' | sort -nr
        working-directory: ./

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure using Azure CLI
        run: |
          az webapp deploy --resource-group dujour-mobile_group --name dujour-mobile --src-path ./dujour-mobile/deploy.zip

      - name: Verify deployment
        run: |
          curl -X POST https://dujour-mobile.scm.azurewebsites.net/api/command \
          -d '{"command": "ls -la", "dir": "site\\wwwroot"}' \
          -H 'Authorization: Bearer ${{ secrets.AZURE_SECRET }}' \
          -H 'Content-Type: application/json'
