# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dujour-mobile

on:
  push:
    branches:
      - main
    paths:
      - 'dujour-mobile/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  setup-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        working-directory: ./dujour-mobile/server
        run: npm install

      - name: Install client dependencies
        working-directory: ./dujour-mobile/client
        run: npm install

      - name: List contents of public directory
        working-directory: ./dujour-mobile/client
        run: ls -al ./public/

      - name: Build client application
        working-directory: ./dujour-mobile/client
        run: npm run build

      - name: Zip client build for deployment
        run: zip -r client-build.zip ./dujour-mobile/client/build

      - name: Upload client build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dujour-mobile-client-build
          path: client-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: setup-build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download client build artifact
        uses: actions/download-artifact@v3
        with:
          name: dujour-mobile-client-build

      - name: Unzip client build artifact
        run: unzip client-build.zip -d ./deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          secret: ${{ secrets.AZURE_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'openidConnect'
          federated-token: ${{ steps.auth.outputs.federated-token }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dujour-mobile'
          slot-name: 'Production'
          package: ./deploy
